# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [52]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [57]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])
print(a1)
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[4,5,6],[7,8,9]])
print(a2)

[1 2 3]
[[4 5 6]
 [7 8 9]]


In [59]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
a1=np.array([1,2,3])
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [62]:
# Attributes of 2-dimensional array
a2=np.array([[1,2,3],[4,5,6]])
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [65]:
# Create an array of shape (5, 5) with only ones
a=np.ones([5,5],dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [67]:
# Create an array of shape (3, 3, 5) with only zeros
a=np.zeros([3,3,5],dtype=int)
a

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [68]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=(7,2))

array([[3, 5],
       [7, 6],
       [9, 8],
       [8, 0],
       [9, 9],
       [6, 6],
       [3, 9]])

In [71]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_arr_floats = 1*np.random.random_sample((3,5))
print(random_arr_floats)

[[0.15770199 0.97901794 0.2603523  0.11652538 0.67258067]
 [0.77550745 0.57502512 0.87783979 0.42491018 0.73771878]
 [0.12984133 0.58531022 0.74817892 0.05882971 0.92054457]]


In [72]:
# Create an array of normally distributed random numbers
arr_random = np.random.randint(5,size=(2,5))
print(arr_random)

[[4 1 4 3 0]
 [4 1 1 3 4]]


In [73]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
import random
np.random.seed(42)
rand_arr1 = np.random.randint(0,10,size=(4,6))
print(rand_arr1)


[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [74]:
# Copy the code from the cell above and run it again
import random
np.random.seed(42)
rand_arr1 = np.random.randint(0,10,size=(4,6))
print(rand_arr1)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [76]:
# Find the 0'th index of the latest array you created
a1[0]

1

In [77]:
# Get the first 2 rows of latest array you created
a1

array([1, 2, 3])

In [80]:
# Get the first 2 values of the first 2 rows of the latest array

In [5]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
import numpy as np
a = np.random.randint(0,10,size=(3,5))
print(a)
a1 = np.ones([3,5],dtype = int)
print(a1)

[[7 3 9 2 9]
 [8 8 7 3 1]
 [5 6 5 2 7]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
# Add the two arrays together
a+a1

array([[ 8,  4, 10,  3, 10],
       [ 9,  9,  8,  4,  2],
       [ 6,  7,  6,  3,  8]])

In [8]:
# Create another array of ones of shape (5, 3)
b1 = np.ones([5,3],dtype=int)
print(b1)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
a+b1


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [19]:
# Do the same operation you just did but this time with a transpose on one array
at = b1.transpose()
print(at)
b=a+at
print(b)



[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[ 8  4 10  3 10]
 [ 9  9  8  4  2]
 [ 6  7  6  3  8]]


In [22]:
# Take the latest array to the power of 2 using the python way
np.exp(b)


array([[2.98095799e+03, 5.45981500e+01, 2.20264658e+04, 2.00855369e+01,
        2.20264658e+04],
       [8.10308393e+03, 8.10308393e+03, 2.98095799e+03, 5.45981500e+01,
        7.38905610e+00],
       [4.03428793e+02, 1.09663316e+03, 4.03428793e+02, 2.00855369e+01,
        2.98095799e+03]])

In [24]:
# Do the same thing with numpy way
np.power(b,2)


array([[ 64,  16, 100,   9, 100],
       [ 81,  81,  64,  16,   4],
       [ 36,  49,  36,   9,  64]], dtype=int32)

In [26]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(b)
np.min(b)
np.max(b)
np.std(b)
np.var(b)


6.782222222222223

In [28]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a = np.random.randint(10,size=(3,3))
print(a)
b = np.random.randint(10,size=(3,2))
print(b)


[[7 9 7]
 [7 9 5]
 [9 6 7]]
[[4 9]
 [2 3]
 [2 7]]


In [29]:
# Perform a dot product on the two newest arrays you created
np.dot(a,b)


array([[ 60, 139],
       [ 56, 125],
       [ 62, 148]])

In [32]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
a = np.random.randint(10,size=(4,3))
print(a)
b = np.random.randint(10,size=(4,3))
print(b)




[[7 2 9]
 [6 8 7]
 [0 6 4]
 [5 7 6]]
[[7 3 0]
 [7 9 2]
 [2 6 9]
 [1 1 7]]


In [33]:
# Perform a hadamard product on the two newest arrays you created
a*b


array([[49,  6,  0],
       [42, 72, 14],
       [ 0, 36, 36],
       [ 5,  7, 42]])

In [34]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(a,b)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [41]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
a1=a.transpose()
print(a1)
print(b1)
np.dot(a1,b)


[[7 6 0 5]
 [2 8 6 7]
 [9 7 4 6]]
[[7 7 2 1]
 [3 9 6 1]
 [0 2 9 7]]


array([[ 96,  80,  47],
       [ 89, 121, 119],
       [126, 120,  92]])

In [43]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
c=np.random.randint(10,size=(3,3))
print(c)
d=np.random.randint(10,size=(3,3))
print(d)




[[8 0 6]
 [8 0 9]
 [8 8 2]]
[[1 2 9]
 [7 3 1]
 [2 4 5]]


In [44]:
# Compare the two arrays with '>', '<=' and '==' 
c>d
c<=d
c==d

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [45]:
# Sort one of the arrays you just created in ascending order
np.argsort(c)

array([[1, 2, 0],
       [1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [46]:
# Sort the indexes of one of the arrays you just created
np.argmax(c)

5

In [47]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(c,axis=0)


array([0, 2, 1], dtype=int64)

In [49]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr10=np.random.randint(10,size=(1,100))
arr10


array([[8, 1, 7, 6, 4, 8, 9, 4, 3, 8, 5, 9, 3, 6, 4, 4, 5, 3, 8, 1, 2, 1,
        0, 9, 7, 3, 2, 3, 9, 4, 5, 8, 2, 3, 8, 9, 4, 0, 2, 5, 8, 0, 5, 3,
        6, 1, 1, 2, 8, 0, 7, 0, 5, 9, 4, 0, 7, 9, 5, 8, 2, 4, 4, 1, 8, 8,
        4, 5, 3, 7, 1, 8, 0, 6, 6, 1, 5, 5, 1, 5, 5, 1, 9, 1, 5, 7, 2, 6,
        2, 5, 0, 5, 8, 8, 5, 6, 3, 7, 3, 0]])

In [50]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(arr10)

6

In [51]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(arr10)

22